apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: registry.cn-hangzhou.aliyuncs.com/hxpdocker/ks-guestbook-demo:0.2
        name: guestbook-ui
        ports:
        - containerPort: 80
